### ISSUE TITLE
Random questions should be more evently spaced throughout the day

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#8]
- I plan on doing this by increasing the minimum time spacing to something large, rather than making multiple copies of the random questionarire for different bins in the day.
- In order to do this,  the random times needs to be more efficient.  I can copy this from my other code.

Assignee: me

**Comment by rkdarst** [comment]
In aware-core I've done my optimization of `random_times`, and made the random schedules predictable and idempotent (so that if you reschedule, you don't get repeats through the day).

Still need to make the questions more evenly distributed...

**Comment by rkdarst** [comment]
@AnaTomomi, about this:  the granularity of random bins is one hour.  So if we make three approximately equal bins, then:  they are probably not exactly equally sized (since you likely can't divide the number of hours by three, minor problem) and either there is a one hour gap minimum gap, or zero hour minimum gap.

I went ahead and did the above solution with one hour gaps, but we will need to change again probably.

I would propose a better method.  Lets say time interval is `start` to `end`.  Make minimum interval be `end-start / 4`.  That way the questions are guaranteed to cover at least half the day, and they are spaced well.

**Comment by AnaTomomi** [comment]
Thanks for the info. This needs to be talked with Talayeh since she explained how it worked on the beginning.

Remember that start and end date are set by the user and although, the minimum range is 12 hours, it could also be bigger and odd (e.g. 13) which would lead to the same problem. If I understood you correctly, I would suggest something like:

morning=[start_hour, start_hour+2]
evening=[end_hour -2, end_hour]
for olo:
def_int=round(end_hour - start_hour)/times 
OLO1 = [start_hour + 2, start_hour+2+def_int]
OLO2=[start_hour+2+def_int, start_hour+2+2*def_int]
OLO3=[start_hour+2+def_int, start_hour+2+3*def_int]

**Comment by rkdarst** [comment]
This is roughly what I'm doing.  So I guess it will work...

Here is the current code of the hours selection (the start+2, end-2 came from what was there before).  All these variables are the hours.  There is a gap of one hour (-2 for the end of first and second intervals) to make sure that they aren't less than 30 minutes.

```
        int olo1_start = startHour + 2;
        int olo3_end   = endHour - 2;
        int olo2_start = (int) round( olo1_start + (olo3_end-olo1_start)/3.);
        int olo3_start = (int) round( olo1_start + 2*(olo3_end-olo1_start)/3.);
        int olo1_end   = olo2_start-2;
        int olo2_end   = olo3_start - 2;
```

Alternatively we can abandon this and go to the original strategy of one random scheduler, with min interval=3 hours, which means that we cover a span of at least 6h of the day, which is probably effectively pretty similar to this.

**Comment by rkdarst** [comment]
In a commit.  Closing.
